Correctly use PTR_ERR in pcie_bf_mimo_ctrl_decode
Correctly use PTR_ERR instead of cast to unsigned int in
pcie_bf_mimo_ctrl_decode if fp_data pointer contains errors.

This fix a compilation warning on 64Bit:

/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/mwlwifi-2023-04-29-6a436714/hif/pcie/pcie.c:1325:37: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
1325 | filename, (unsigned int)fp_data);
| ^

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>